[versions]
androidGradlePlugin = "7.3.1"
appCompat = "1.6.1"
commonsCodec = "1.15"
compileSdk = "33"
constraintLayout = "2.1.4"
coreTesting = "2.1.0"
coroutines = "1.4.2"
datastorePreferences = "1.0.0"
espresso = "3.4.0"
fragment = "1.5.6"
glide = "4.14.2"
gson = "2.9.1"
junit = "4.13.2"
kotlin = "1.7.21"
ktx = "1.9.0"
lifecycle = "2.5.1"
material = "1.6.0"
minSdk = "27"
navigation = "2.5.3"
okhttpLogging = "4.10.0"
paging = "3.1.1"
preference = "1.2.0"
retrofit = "2.9.0"
room = "2.5.1"
runner = "1.0.1"
swiperefreshlayout = "1.1.0"
targetSdk = "31"
truth = "0.42"
testExtJunit = "1.1.3"
uiAutomator = "2.2.0"
viewpager2 = "1.1.0-beta01"
webkit = "1.6.0"
webpdecoder = "2.3.4.14.2"
work = "2.7.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
webpdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "webpdecoder" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
#Keep using the Java plugin as the temp workaround for the Kotlin one does not generate setter for parameters with default values
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }